gogobuy/gogobuy/Controllers/BuyerSellerController.cs
using gogobuy.Models;
using gogobuy.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace gogobuy.Controllers
{
    public class BuyerSellerController : Controller
    {
        #region 商品上架
        public ActionResult BuyerUpload()
        {
            if (Session[CDictionary.SK_LOGINED_USER_EMAIL] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            return View();
        }
        [HttpPost]
        public ActionResult BuyerUpload(UploadViewModel product)
        {

            if (!ModelState.IsValid)
                return View(product);


            int userId = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            string[] tempPhotoName = new string[product.photo.Count];

            for (int i = 0; i < product.photo.Count; i++)
            {
                string savePath = Server.MapPath("~/Content/img/Product/");
                string phtoName = Guid.NewGuid().ToString() + ".jpg";
                tempPhotoName[i] = phtoName;
                string saveResult = savePath + phtoName;
                product.photo[i].SaveAs(saveResult);
            }

            using (var db = new gogobuydbEntities()) {

                var wishProd = new tProduct()
                {
                    fMemberID = userId,
                    fCategory = product.fCategory,
                    fDescription = product.fDescription,
                    fPrice = product.fPrice,
                    fQuantity = product.fQuantity,
                    fProductName = product.fProductName,
                    fProductLocation = product.fProductLocation,
                    fImgPath = tempPhotoName[0],
                    fIsWish = true,
                    fUpdateTime = DateTime.Now
                };
                db.tProduct.Add(wishProd);
                db.SaveChanges();
                
                int productID = wishProd.fProductID;
                for(int i = 0; i < tempPhotoName.Length; i++) {
                    bool isCover = false;
                    if (i == 0)
                        isCover = true;
                    var wishPhoto = new tProductImage()
                    {
                        fProductID = productID,
                        fCover = isCover,
                        fImgPath = tempPhotoName[i]
                    };
                    db.tProductImage.Add(wishPhoto);
                }
                db.SaveChanges();

            }
            return RedirectToAction("BuyerManagement");
        }
        #endregion
        #region 許願商品上架
        public ActionResult SellerUpload()
        {
            if (Session[CDictionary.SK_LOGINED_USER_EMAIL] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            return View();
        }
        [HttpPost]
        public ActionResult SellerUpload(UploadViewModel product)
        {
            if (!ModelState.IsValid)
                return View(product);


            int userId = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            string[] tempPhotoName = new string[product.photo.Count];

            for (int i = 0; i < product.photo.Count; i++)
            {
                string savePath = Server.MapPath("~/Content/img/Product/");
                string phtoName = Guid.NewGuid().ToString() + ".jpg";
                tempPhotoName[i] = phtoName;
                string saveResult = savePath + phtoName;
                product.photo[i].SaveAs(saveResult);
            }

            using (var db = new gogobuydbEntities())
            {

                var wishProd = new tProduct()
                {
                    fMemberID = userId,
                    fCategory = product.fCategory,
                    fDescription = product.fDescription,
                    fPrice = product.fPrice,
                    fQuantity = product.fQuantity,
                    fProductName = product.fProductName,
                    fProductLocation = product.fProductLocation,
                    fImgPath = tempPhotoName[0],
                    fIsWish = false,
                    fUpdateTime = DateTime.Now
                };
                db.tProduct.Add(wishProd);
                db.SaveChanges();

                int productID = wishProd.fProductID;
                for (int i = 0; i < tempPhotoName.Length; i++)
                {
                    bool isCover = false;
                    if (i == 0)
                        isCover = true;
                    var wishPhoto = new tProductImage()
                    {
                        fProductID = productID,
                        fCover = isCover,
                        fImgPath = tempPhotoName[i]
                    };
                    db.tProductImage.Add(wishPhoto);
                }
                db.SaveChanges();

            }
            return RedirectToAction("SellerManagement");
        }
        #endregion
        public ActionResult BuyerManagement()
        {
            if (Session[CDictionary.SK_LOGINED_USER_EMAIL] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var db = new gogobuydbEntities();
            int userId = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            var wishProd = from w in db.tProduct
                           where w.fIsWish == true && w.fMemberID == userId
                           select w;
            List<ProductViewModel> list = new List<ProductViewModel>();
            foreach(var wishProds in wishProd)
            {
                list.Add(new ProductViewModel { fProductID = wishProds.fProductID, fProductName = wishProds.fProductName,
                fImgPath = wishProds.fImgPath, fPrice = wishProds.fPrice, fQuantity = wishProds.fQuantity, fUpdateTime = wishProds.fUpdateTime});
            }
            return View(list);
        }
        public ActionResult SellerManagement()
        {
            if (Session[CDictionary.SK_LOGINED_USER_EMAIL] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var db = new gogobuydbEntities();
            int userId = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            var wishProd = from w in db.tProduct
                           where w.fIsWish == false && w.fMemberID == userId
                           select w;
            List<ProductViewModel> list = new List<ProductViewModel>();
            foreach (var wishProds in wishProd)
            {
                list.Add(new ProductViewModel
                {
                    fProductID = wishProds.fProductID,
                    fProductName = wishProds.fProductName,
                    fImgPath = wishProds.fImgPath,
                    fPrice = wishProds.fPrice,
                    fQuantity = wishProds.fQuantity,
                    fUpdateTime = wishProds.fUpdateTime
                });
            }
            return View(list);
        }
        public ActionResult BucketListDetails(int productID)
        {
            if (Session[CDictionary.SK_LOGINED_USER_EMAIL] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var db = new gogobuydbEntities();
            int userId = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            var wishProdInfo = db.tProduct.Where(p => p.fMemberID == userId && p.fProductID == productID).FirstOrDefault();
            //var imgPaths = db.tProductImage.Where(p => p.fProductID == productID).Select(p => p.fImgPath);
            
            UploadViewModel wishProduct = new UploadViewModel()
            {
                fProductID = wishProdInfo.fProductID,
                fProductName = wishProdInfo.fProductName,
                fCategory = wishProdInfo.fCategory,
                fDescription = wishProdInfo.fDescription,
                fPrice = wishProdInfo.fPrice,
                fQuantity = wishProdInfo.fQuantity,
                fProductLocation = wishProdInfo.fProductLocation
            };
            //foreach(var imgPath in imgPaths)
            //{
            //    wishProduct.imgName.Add(imgPath);
            //}
            return View(wishProduct);
        }
        [HttpPost]
        public ActionResult BucketListDetails(UploadViewModel wishProduct)
        {
            var db = new gogobuydbEntities();
            tProduct wishEdit = db.tProduct.Where(p=>p.fProductID == wishProduct.fProductID).First();
            wishEdit.fProductName = wishProduct.fProductName;
            wishEdit.fCategory = wishProduct.fCategory;
            wishEdit.fDescription = wishProduct.fDescription;
            wishEdit.fProductLocation = wishProduct.fProductLocation;
            wishEdit.fPrice = wishProduct.fPrice;
            wishEdit.fQuantity = wishProduct.fQuantity;
            wishEdit.fUpdateTime = DateTime.Now;
            db.SaveChanges();
            return RedirectToAction("BuyerManagement");
        }
        public ActionResult SellListDetails(int productID)
        {
            if (Session[CDictionary.SK_LOGINED_USER_EMAIL] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var db = new gogobuydbEntities();
            int userId = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            var prodInfo = db.tProduct.Where(p => p.fMemberID == userId && p.fProductID == productID).FirstOrDefault();
            //var imgPaths = db.tProductImage.Where(p => p.fProductID == productID).Select(p => p.fImgPath);

            UploadViewModel product = new UploadViewModel()
            {
                fProductID = prodInfo.fProductID,
                fProductName = prodInfo.fProductName,
                fCategory = prodInfo.fCategory,
                fDescription = prodInfo.fDescription,
                fPrice = prodInfo.fPrice,
                fQuantity = prodInfo.fQuantity,

gogobuy/gogobuy/Controllers/CollectController.cs
using gogobuy.Models;
using gogobuy.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace gogobuy.Controllers
{
    public class CollectController : Controller
    {
        // GET: Collect
        public ActionResult Collection()
        {
            if (Session[CDictionary.SK_LOGINED_USER_ID] == null)
                return RedirectToAction("Login", "Home");
            
            var db = new gogobuydbEntities();
            int id = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            var queryCollections = db.tCollection.Where(c => c.fMemberID == id)
                .Join(db.tProduct,
                c => c.fProductID,
                p => p.fProductID,
                (c, p) => new 
                {
                    c.fCollectID,
                    c.fProductID,
                    p.fProductName,
                    p.fImgPath,
                    p.fPrice
                })
                .OrderByDescending(c => c.fCollectID);
            List <CollectViewModel> collections = new List<CollectViewModel>();
            foreach (var collection in queryCollections)
            {
                collections.Add(new CollectViewModel { fProductID = collection.fProductID,fProductName = collection.fProductName, 
                    fImgPath = collection.fImgPath, fPrice = collection.fPrice});
            }
            return View(collections);
        }

        public ActionResult Delete(int productID)
        {
            if (Session[CDictionary.SK_LOGINED_USER_ID] == null)
                return Json("login");
            int userID = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            var db = new gogobuydbEntities();
            tCollection collection = db.tCollection.FirstOrDefault(c => c.fProductID == productID && c.fMemberID == userID);
            if (collection != null)
            {
                db.tCollection.Remove(collection);
                db.SaveChanges();
                return Json("success");
            }
            return Json("fail");
        }

        public ActionResult Likeitem(int productID) {
            // 抓取使用者有無登入
            if (Session[CDictionary.SK_LOGINED_USER_ID] == null)
                return Json("login");

            int userID = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            var db = new gogobuydbEntities();
            var collection = new tCollection
            {
                fMemberID = userID,
                fProductID = productID
            };
            db.tCollection.Add(collection);
            db.SaveChanges();

            return Json("success");
        }
    }
}

gogobuy/gogobuy/Controllers/DetailsController.cs
using gogobuy.Models;
using gogobuy.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace gogobuy.Controllers
{
    public class DetailsController : Controller
    {
        // GET: Details
        public ActionResult ProductDetails(int fProductID)
        {
            int userId = -1;
            // 預設使用者未收藏商品
            bool isLike = false;
            // 抓取user是否登入
            if (Session[CDictionary.SK_LOGINED_USER_ID] != null)
                userId = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            //Create a ViewModel and New it here when you want to use more than one table
            ProductDetailsViewModel pdViewModel = new ProductDetailsViewModel();

            //Use entity framework to import db which could use in C#
            gogobuydbEntities db = new gogobuydbEntities();

            var tP = db.tProduct.Where(t => t.fProductID == fProductID).FirstOrDefault();
            var tPDetails = db.tProductDetails.Where(t => t.fProductID == fProductID).FirstOrDefault();
            var tPImage = db.tProductImage.Where(t => t.fProductID == fProductID);
            var tMemberShip = db.tMembership.Where(t => t.fMemberID == tP.fMemberID).FirstOrDefault();
            // 若是有登入查看使用者是否收藏商品
            if (userId != -1)
            {
                var collection = db.tCollection.FirstOrDefault(c => c.fMemberID == userId && c.fProductID == fProductID);
                if (collection != null)
                    isLike = true;
            }
            //FirstOrDefault: to ensure that obtaining only "one" piece of data,
            //                if there's no data, default would be set

            //Add column of table into ViewModel
            pdViewModel.fCategory = tP.fCategory;
            pdViewModel.fProductName = tP.fProductName;
            pdViewModel.fPrice = tP.fPrice;
            pdViewModel.fDescription = tP.fDescription;
            pdViewModel.fArrivalTime = tP.fArrivalTime;
            pdViewModel.fUpdateTime = tP.fUpdateTime;
            pdViewModel.fProductLocation = tP.fProductLocation;
            pdViewModel.fQuantity = tP.fQuantity;
            pdViewModel.fImgPath = db.tProductImage.Where(p => p.fCover == true && p.fProductID == fProductID).Select(p => p.fImgPath).FirstOrDefault();
            //pdViewModel.fImgPath = db.tProductImage.Where(p => p.fCover == true && p.fProductID==fProductID).Select(p => new { p.fImgPath }).FirstOrDefault().ToString();

            pdViewModel.fProductID = tP.fProductID;
            pdViewModel.fMemberID = tP.fMemberID;

            pdViewModel.fFirstName = tMemberShip.fFirstName;
            pdViewModel.fLastName = tMemberShip.fLastName;
            pdViewModel.isLike = isLike;

            foreach (var f in tPImage)
            {
                pdViewModel.listImgPath.Add(f.fImgPath);
            }

            return View(pdViewModel);
        }


        public ActionResult BucketListDetails(int fProductID)
        {
            ProductDetailsViewModel pdViewModel = new ProductDetailsViewModel();

            gogobuydbEntities db = new gogobuydbEntities();

            var tProduct = db.tProduct.Where(p => p.fProductID == fProductID).FirstOrDefault();
            var tPMemberShip = db.tMembership.Where(p => p.fMemberID == tProduct.fMemberID).FirstOrDefault();
            var tPDetails = db.tProductDetails.Where(p => p.fProductID == fProductID);
            var tPImages = db.tProductImage.Where(p => p.fProductID == fProductID).OrderBy(p => p.fImgPath);

            pdViewModel.fProductID = tProduct.fProductID;
            pdViewModel.fProductName = tProduct.fProductName;
            pdViewModel.fPrice = tProduct.fPrice;
            pdViewModel.fMemberID = tProduct.fMemberID;
            pdViewModel.fProductLocation = tProduct.fProductLocation;
            pdViewModel.fQuantity = tProduct.fQuantity;
            pdViewModel.fUpdateTime = tProduct.fUpdateTime;
            pdViewModel.fArrivalTime = tProduct.fArrivalTime;
            pdViewModel.fCategory = tProduct.fCategory;
            pdViewModel.fDescription = tProduct.fDescription;

            pdViewModel.fFirstName = tPMemberShip.fFirstName;
            pdViewModel.fLastName = tPMemberShip.fLastName;

            //pdViewModel.fPname = tPDetails.fPName;

            pdViewModel.fImgPath = db.tProductImage.Where(p => p.fProductID == fProductID && p.fCover == true).Select(p => p.fImgPath).FirstOrDefault();
            pdViewModel.fPname = db.tProductDetails.Where(p => p.fProductID == fProductID).Select(p => p.fPName).FirstOrDefault();

            foreach (var f in tPImages)
            {
                pdViewModel.listImgPath.Add(f.fImgPath);
            }

            foreach (var f in tPDetails)
            {
                pdViewModel.listStyle.Add(f.fPName);
            }

            return View(pdViewModel);
        }
    }
}

gogobuy/gogobuy/Views/BuyerSeller/BuyerManagement.cshtml
@using gogobuy.ViewModels;
@model List<ProductViewModel>
@{
    ViewBag.Title = "BuyerManagement";
}

<head>
    <style>
        .sm-img {
            width: 150px;
            height: 150px;
        }
        .setting-icon {
            width: 30px;
            height: 30px;
        }
        /* Table Head */
        #table-5 thead th {
            background-color: #F9F9F9;
            color: #515151;
            border-bottom-width: 0;
        }
        /* 表格rwd */
        .rwd-table {
            background: #DDDDDD;
            overflow: hidden;
        }

            .rwd-table tr:nth-of-type(2n) {
                background: #EDEDED
            }

            .rwd-table th,
            .rwd-table td {
                margin: 0.5em 1em;
            }

        .rwd-table {
            min-width: 100%;
        }

            .rwd-table th {
                display: none;
            }

            .rwd-table td {
                display: block;
            }

                .rwd-table td:before {
                    content: attr(data-th) " : ";
                    font-weight: bold;
                    width: 6.5em;
                    display: inline-block;
                }

            .rwd-table th,
            .rwd-table td {
                text-align: left;
            }

                .rwd-table th,
                .rwd-table td:before {
                    color: #515151ff;
                    font-weight: bold;
                }

        @@media (min-width: 960px) {
            .rwd-table td:before {
                display: none;
            }

            .rwd-table th,
            .rwd-table td {
                display: table-cell;
                padding: 0.25em 0.5em;
            }

                .rwd-table th:first-child,
                .rwd-table td:first-child {
                    padding-left: 0;
                }

                .rwd-table th:last-child,
                .rwd-table td:last-child {
                    padding-right: 0;
                }

            .rwd-table th,
            .rwd-table td {
                padding: 1em !important;
            }
        }
    </style>
</head>
<a class="btn btn-primary mx-2 my-2" href="@Url.Action("BuyerUpload", "BuyerSeller")" style="width: 100px;">商品許願</a>
<div class="row justify-content-center"> 
    <div class="table-responsive-sm">
        <table class="rwd-table">
            <thead>
                <tr>
                    <th scope="col">圖片</th>
                    <th scope="col">商品名稱</th>
                    <th scope="col">收購價格</th>
                    <th scope="col">收購數量</th>
                    <th scope="col">更新日期</th>
                    <th scope="col">管理</th>
                    <th scope="col">刪除</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var wishProds in Model)
                    {
                        <tr>
                            <td data-th="圖片"><img src="~/Content/img/Product/@wishProds.fImgPath" class="sm-img"></td>
                            <td data-th="商品名稱">
                                @wishProds.fProductName
                            </td>
                            <td data-th="收購價格">$@String.Format("{0:0}", wishProds.fPrice)</td>
                            <td data-th="收購數量">@wishProds.fQuantity</td>
                            <td data-th="更新日期">@String.Format("{0:yyyy/MM/dd}", wishProds.fUpdateTime)</td>
                            <td data-th="管理"><a href="~/BuyerSeller/BucketListDetails?productID=@wishProds.fProductID"><img src="~/Content/img/buyer_seller/settings.png" class="setting-icon"></a></td>
                            <td data-th="刪除"><a href=""><i class="fa fa-trash" style="color: #b51b0d;"></i></a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

gogobuy/gogobuy/Views/BuyerSeller/ProductList.cshtml
@using gogobuy.ViewModels;
@model List<ProductViewModel>
@{
    ViewBag.Title = "ProductList";
}
<head>

    <style>
        .item {
            width: 98%;
            height: 60%;
            margin: 0 auto;
        }

            .item > img {
                padding-top: 10px;
                padding-bottom: 10px;
                width: 100%;
                height: 100%;
            }

        .item-name {
            display: -webkit-box;
            width: 95%;
            height: 38px;
            margin: 0 auto;
            font-size: 0.95rem;
            line-height: 1.2rem;
            overflow: hidden;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 2;
        }

        .price {
            font-size: 0.95rem;
            padding: 3px 0;
        }

        div.col-md-2.border {
            height: 280px;
        }

        .h5 {
            font-size: 1rem;
        }
        .like {
            cursor: pointer;
        }
    </style>
</head>
@*分類區塊*@
<section class="container my-5" style="background: linear-gradient(180deg, #FFFFFF 0%, rgba(255, 255, 255, 0) 100%), #9fff99;">
    <h4 class="my-3 mx-5">分類：</h4>
    <div class="row text-center d-flex justify-content-between">
        <div class="col-md-1 col-sm-4 col-4 border border-success rounded">
            <a href="@Url.Action("ProductList", new { category = "手機周邊"})" class="link-success">
                <img src="~/Content/img/index/smartphone.png" style="width:100%; max-width: 50px; " />
                <div class="h5">手機周邊</div>
            </a>
        </div>
        <div class="col-md-1 col-sm-4 col-4 border border-success rounded">
            <a href="@Url.Action("ProductList", new { category = "3C產品"})" class="link-success">
                <img src="~/Content/img/index/pc.png" style="width:100%; max-width: 50px; " />
                <div class="h5">3C產品</div>
            </a>
        </div>
        <div class="col-md-1 col-sm-4 col-4  border border-success rounded">
            <a href="@Url.Action("ProductList", new { category = "生活居家"})" class="link-success">
                <img src="~/Content/img/index/shopping-bag.png" style="width: 100%; max-width: 50px; " />
                <div class="h5">生活居家</div>
            </a>
        </div>
        <div class="col-md-1 col-sm-4 col-4 border border-success rounded">
            <a href="@Url.Action("ProductList", new { category = "服飾飾品"})" class="link-success">
                <img src="~/Content/img/index/male-clothes.png" style="width: 100%; max-width: 50px; " />
                <div class="h5">服飾飾品</div>
            </a>
        </div>
        <div class="col-md-1 col-sm-4 col-4 border border-success rounded">
            <a href="@Url.Action("ProductList", new { category = "名產食品"})" class="link-success">
                <img src="~/Content/img/index/snack.png" style="width: 100%; max-width: 50px; " />
                <div class="h5">名產食品</div>
            </a>
        </div>
        <div class="col-md-1 col-sm-4 col-4 border border-success rounded">
            <a href="@Url.Action("ProductList", new { category = "文創書籍"})" class="link-success">
                <img src="~/Content/img/index/book.png" style="width: 100%; max-width: 50px; " />
                <div class="h5">文創書籍</div>
            </a>
        </div>
        <div class="col-md-1 col-sm-4 col-4 border border-success rounded">
            <a href="@Url.Action("ProductList", new { category = "影音周邊"})" class="link-success">
                <img src="~/Content/img/index/cd-player.png" style="width: 100%; max-width: 50px; " />
                <div class="h5">影音周邊</div>
            </a>
        </div>
        <div class="col-md-1 col-sm-4 col-4 border border-success rounded">
            <a href="@Url.Action("ProductList", new { category = "古董古玩"})" class="link-success">
                <img src="~/Content/img/index/vase.png" style="width: 100%; max-width: 50px; " />
                <div class="h5">古董古玩</div>
            </a>
        </div>
        <div class="col-md-1 col-sm-4 col-4 border border-success rounded">
            <a href="@Url.Action("ProductList", new { category = "其他"})" class="link-success">
                <img src="~/Content/img/index/megaphone.png" style="width: 100%; max-width: 50px; " />
                <div class="h5">其他</div>
            </a>
        </div>
    </div>
</section>
@*分類區塊*@
<img src="~/Content/img/index/b_ornament_121_0M.png" style="width:100%;" />
<section class="container" style="background: linear-gradient(180deg, #FFFFFF 0%, rgba(255, 255, 255, 0) 100%), #CFFFCC;">
    <h4 class="my-3 mx-5">販售商品總覽：</h4>
    <div class="row text-center d-flex justify-content-start">
        @{
            foreach (var p in Model)
            {
                <div class="col-md-2 col-sm-3 col-6 border border-success">
                    <a href=@Url.Action("ProductDetails", "Details", new { fProductID = p.fProductID }) class="link-success">
                        <div class="item">
                            <img src="~/Content/img/Product/@p.fImgPath" />
                        </div>
                        <div class="item-name">@p.fProductName</div>
                    </a>
                    <div class="d-flex align-items-center justify-content-between price">
                        價格$@String.Format("{0:0}", p.fPrice)
                        @{ if (p.isLike)
                            {
                                <img src="~/Content/img/img_memberCenter/heart.png" style="width:100%; max-width:30px;" id="@p.fProductID" class="like" />
                            }
                            else
                            {
                                <img src="~/Content/img/img_memberCenter/unlike.png" style="width:100%; max-width:30px;" id="@p.fProductID" class="like" />
                            }
                        }
                    </div>
                    <div class="d-flex align-content-end justify-content-end">
                        <small>@p.fProductLocation</small>
                    </div>
                </div>
            }
        }
    </div>
</section>
<img src="~/Content/img/index/b_ornament_121_0M.png" style="width:100%;" />

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="d-flex justify-content-end">
                <button type="button" class="btn-close m-2" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                要使用此功能，請先登入會員！
            </div>
            <div class="d-flex justify-content-end">
                <button type="button" class="btn btn-outline-secondary m-2" data-bs-dismiss="modal">關閉</button>
                <a href=@Url.Action("Login", "home") class="btn btn-primary  m-2">登入</a>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('img.like').click(function (event) {
            var productID = event.target.id;
            if ($(this).attr('src') == '/Content/img/img_memberCenter/unlike.png') {
                $.ajax({
                    url: "@Url.Action("LikeItem", "Collect")",
                    type: 'post',
                    data: {
                        productID: productID
                    },
                    async: true,
                    success: function (data) {
                        if (data == 'success') {
                            $('#' + productID).attr('src', '/Content/img/img_memberCenter/heart.png');
                        }
                        if (data == 'login') {
                            $('#myModal').modal('show');
                        }
                    }
                });
            } else {
                $.ajax({
                url: "@Url.Action("Delete", "Collect")",
                type: 'post',
                data: {
                    productID: productID
                },
                async: true,
                success: function (data) {
                    $('#' + productID).attr('src', '/Content/img/img_memberCenter/unlike.png');
                }
                });
            }
        });
    });

</script>