gogobuy/gogobuy/ViewModels/ProductDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace gogobuy.ViewModels
{
    public class ProductDetailsViewModel
    {
        public int fProductID { get; set; }

        public string fProductName { get; set; }

        public decimal? fPrice { get; set; }

        public string fDescription { get; set; }

        public string fCategory { get; set; }

        public string fProductLocation { get; set; }

        public string fImgPath { get; set; }

        public string fArrivalTime { get; set; }

        public int? fQuantity { get; set; }

        public int? fMemberID { get; set; }

        public int fIsWish { get; set; }

        public DateTime? fUpdateTime { get; set; }

        public string fFirstName { get; set; }

        public string fLastName { get; set; }

        public string fPname { get; set; }
        public bool isLike { get; set; }
        public List<string> listImgPath = new List<string>();

        public List<string> listStyle = new List<string>();
    }
}

gogobuy/gogobuy/Controllers/ChatroomController.cs
using gogobuy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using gogobuy.ViewModels;



namespace gogobuy.Controllers
{
    public class ChatroomController : Controller
    {
        // GET: Chatroom
        public ActionResult Chatroom(int? fMemberID)
        {
            if (Session[CDictionary.SK_LOGINED_USER_EMAIL] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            // 獲取user資料


            string email = Session[CDictionary.SK_LOGINED_USER_EMAIL].ToString();
            var db = new gogobuydbEntities();
            tMembership user = db.tMembership.SingleOrDefault(m => m.fEmail == email);
            ViewBag.UserName = user.fFirstName + user.fLastName;



            IEnumerable<tProduct> table = null;

            if(fMemberID > 0)
            { 

                table = from p in (new gogobuydbEntities()).tProduct
                        where p.fMemberID == fMemberID
                        select p;
                return View(table);

            }




            //int count = Convert.ToInt32(Request.Form["Count"]);
            //for (int i = 1; i < count; i++)
            //{

            //    int ProductID = Convert.ToInt32(Request.Form["ProductID" + i]);

            //    string ProductQuantity = Request.Form["ProductQuantity" + i];
            //    string BuyerID = Request.Form["MemberID" + i];
            //    string OrderNote = Request.Form["ProductNote" + i];
            //    string ProductPrice = Request.Form["ProductPrice" + i];
            //    string ProductNote = Request.Form["ProductNote" + i];

            //    int SellerID = (int)Session[CDictionary.SK_LOGINED_USER_ID];

            //    gogobuydbEntities gogobuydb = new gogobuydbEntities();
            //    tProduct prod = gogobuydb.tProduct.FirstOrDefault(m => m.fProductID == ProductID);
            //    if (prod != null)
            //    {
            //        prod.fPrice = decimal.Parse(ProductPrice);

            //        db.SaveChanges();
            //    }

            //    string sql =

            //    "insert into tShopping (fProductID,fMemberID,fQuantity,fShoppingNote) values(@K_FPRODUCTID,@K_FMEMBERID,@K_FQUANTITY,@K_SHOPPINGNOTE)";


            //    List<SqlParameter> paras = new List<SqlParameter>();

            //    paras.Add(new SqlParameter("K_FPRODUCTID", (object)ProductID));

            //    paras.Add(new SqlParameter("K_FQUANTITY", (object)ProductQuantity));

            //    paras.Add(new SqlParameter("K_FMEMBERID", (object)SellerID));

            //    paras.Add(new SqlParameter("K_SHOPPINGNOTE", (object)SellerID));


            //    SqlConnection con = new SqlConnection();
            //    con.ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings["ConnDB"].ConnectionString;
            //    con.Open();

            //    SqlCommand cmd = new SqlCommand(sql, con);
            //    if (paras != null)
            //    {
            //        foreach (SqlParameter p in paras)
            //            cmd.Parameters.Add(p);
            //    }

            //    cmd.ExecuteNonQuery();
            //    con.Close();
            //}



            return View();
        }





        public ActionResult Delete(int id)
        {
            IEnumerable<tProduct> table = null;
            

            table = from p in (new gogobuydbEntities()).tProduct
                    where p.fProductID != id
                    select p;        
            return View(table);       




            
        }





        public ActionResult Update()
        {
            return View();
        }





        public ActionResult AddWishOrder()
        {


            int count = Convert.ToInt32(Request.Form["Count"]);
            for (int i = 1; i < count; i++)
            {

                int ProductID = Convert.ToInt32(Request.Form["ProductID" + i]);

                string ProductQuantity = Request.Form["ProductQuantity" + i];
                string BuyerID = Request.Form["MemberID" + i];
                string OrderNote = Request.Form["ProductNote" + i];
                string ProductPrice = Request.Form["ProductPrice" + i];
                string ProductNote = Request.Form["ProductNote" + i];

                int SellerID = (int)Session[CDictionary.SK_LOGINED_USER_ID];

                gogobuydbEntities db = new gogobuydbEntities();
                tProduct prod = db.tProduct.FirstOrDefault(m => m.fProductID == ProductID);
                if (prod != null)
                {
                    prod.fPrice = decimal.Parse(ProductPrice);

                    db.SaveChanges();
                }


                if(Convert.ToInt32(count) >= 1)
                { 


                if (Convert.ToInt32(ProductQuantity) >= 1)
                {

                    string sql =

                    "insert into tShopping (fProductID,fMemberID,fQuantity,fShoppingNote) values(@K_FPRODUCTID,@K_FMEMBERID,@K_FQUANTITY,@K_SHOPPINGNOTE)";


                    List<SqlParameter> paras = new List<SqlParameter>();

                    paras.Add(new SqlParameter("K_FPRODUCTID", (object)ProductID));

                    paras.Add(new SqlParameter("K_FQUANTITY", (object)ProductQuantity));

                    paras.Add(new SqlParameter("K_FMEMBERID", (object)SellerID));

                    paras.Add(new SqlParameter("K_SHOPPINGNOTE", (object)ProductNote));



                    SqlConnection con = new SqlConnection();
                    con.ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings["ConnDB"].ConnectionString;
                    con.Open();

                    SqlCommand cmd = new SqlCommand(sql, con);
                    if (paras != null)
                    {
                        foreach (SqlParameter p in paras)
                            cmd.Parameters.Add(p);
                    }

                    cmd.ExecuteNonQuery();
                    con.Close();


                }
                }
            }

            return Redirect("~/ShoppingCart/Checkout");
        }

    }

    
}

gogobuy/gogobuy/Controllers/CollectController.cs
using gogobuy.Models;
using gogobuy.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace gogobuy.Controllers
{
    public class CollectController : Controller
    {
        // GET: Collect
        public ActionResult Collection()
        {
            if (Session[CDictionary.SK_LOGINED_USER_ID] == null)
                return RedirectToAction("Login", "Home");
            
            var db = new gogobuydbEntities();
            int id = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            var queryCollections = db.tCollection.Where(c => c.fMemberID == id)
                .Join(db.tProduct,
                c => c.fProductID,
                p => p.fProductID,
                (c, p) => new 
                {
                    c.fCollectID,
                    c.fProductID,
                    p.fProductName,
                    p.fImgPath,
                    p.fPrice
                })
                .OrderByDescending(c => c.fCollectID);
            List <CollectViewModel> collections = new List<CollectViewModel>();
            foreach (var collection in queryCollections)
            {
                collections.Add(new CollectViewModel { fProductID = collection.fProductID,fProductName = collection.fProductName, 
                    fImgPath = collection.fImgPath, fPrice = collection.fPrice});
            }
            return View(collections);
        }

        public ActionResult Delete(int productID)
        {
            if (Session[CDictionary.SK_LOGINED_USER_ID] == null)
                return Json("login");
            int userID = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            var db = new gogobuydbEntities();
            tCollection collection = db.tCollection.FirstOrDefault(c => c.fProductID == productID && c.fMemberID == userID);
            if (collection != null)
            {
                db.tCollection.Remove(collection);
                db.SaveChanges();
                return Json("success");
            }
            return Json("fail");
        }

        public ActionResult Likeitem(int productID) {
            // 抓取使用者有無登入
            if (Session[CDictionary.SK_LOGINED_USER_ID] == null)
                return Json("login");

            int userID = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            var db = new gogobuydbEntities();
            var collection = new tCollection
            {
                fMemberID = userID,
                fProductID = productID
            };
            db.tCollection.Add(collection);
            db.SaveChanges();

            return Json("success");
        }
    }
}

gogobuy/gogobuy/Controllers/DetailsController.cs
using gogobuy.Models;
using gogobuy.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace gogobuy.Controllers
{
    public class DetailsController : Controller
    {
        // GET: Details
        public ActionResult ProductDetails(int fProductID)
        {
            int userId = -1;
            // 預設使用者未收藏商品
            bool isLike = false;
            // 抓取user是否登入
            if (Session[CDictionary.SK_LOGINED_USER_ID] != null)
                userId = (int)Session[CDictionary.SK_LOGINED_USER_ID];
            //Create a ViewModel and New it here when you want to use more than one table
            ProductDetailsViewModel pdViewModel = new ProductDetailsViewModel();

            //Use entity framework to import db which could use in C#
            gogobuydbEntities db = new gogobuydbEntities();

            var tP = db.tProduct.Where(t => t.fProductID == fProductID).FirstOrDefault();
            var tPDetails = db.tProductDetails.Where(t => t.fProductID == fProductID).FirstOrDefault();
            var tPImage = db.tProductImage.Where(t => t.fProductID == fProductID);
            var tMemberShip = db.tMembership.Where(t => t.fMemberID == tP.fMemberID).FirstOrDefault();
            // 若是有登入查看使用者是否收藏商品
            if (userId != -1)
            {
                var collection = db.tCollection.FirstOrDefault(c => c.fMemberID == userId && c.fProductID == fProductID);
                if (collection != null)
                    isLike = true;
            }
            //FirstOrDefault: to ensure that obtaining only "one" piece of data,
            //                if there's no data, default would be set

            //Add column of table into ViewModel
            pdViewModel.fCategory = tP.fCategory;
            pdViewModel.fProductName = tP.fProductName;
            pdViewModel.fPrice = tP.fPrice;
            pdViewModel.fDescription = tP.fDescription;
            pdViewModel.fArrivalTime = tP.fArrivalTime;
            pdViewModel.fUpdateTime = tP.fUpdateTime;
            pdViewModel.fProductLocation = tP.fProductLocation;
            pdViewModel.fQuantity = tP.fQuantity;
            pdViewModel.fImgPath = db.tProductImage.Where(p => p.fCover == true && p.fProductID == fProductID).Select(p => p.fImgPath).FirstOrDefault();
            //pdViewModel.fImgPath = db.tProductImage.Where(p => p.fCover == true && p.fProductID==fProductID).Select(p => new { p.fImgPath }).FirstOrDefault().ToString();

            pdViewModel.fProductID = tP.fProductID;
            pdViewModel.fMemberID = tP.fMemberID;

            pdViewModel.fFirstName = tMemberShip.fFirstName;
            pdViewModel.fLastName = tMemberShip.fLastName;
            pdViewModel.isLike = isLike;

            foreach (var f in tPImage)
            {
                pdViewModel.listImgPath.Add(f.fImgPath);
            }

            return View(pdViewModel);
        }


        public ActionResult BucketListDetails(int fProductID)
        {
            ProductDetailsViewModel pdViewModel = new ProductDetailsViewModel();

            gogobuydbEntities db = new gogobuydbEntities();

            var tProduct = db.tProduct.Where(p => p.fProductID == fProductID).FirstOrDefault();
            var tPMemberShip = db.tMembership.Where(p => p.fMemberID == tProduct.fMemberID).FirstOrDefault();
            var tPDetails = db.tProductDetails.Where(p => p.fProductID == fProductID);
            var tPImages = db.tProductImage.Where(p => p.fProductID == fProductID).OrderBy(p => p.fImgPath);

            pdViewModel.fProductID = tProduct.fProductID;
            pdViewModel.fProductName = tProduct.fProductName;
            pdViewModel.fPrice = tProduct.fPrice;
            pdViewModel.fMemberID = tProduct.fMemberID;
            pdViewModel.fProductLocation = tProduct.fProductLocation;
            pdViewModel.fQuantity = tProduct.fQuantity;
            pdViewModel.fUpdateTime = tProduct.fUpdateTime;
            pdViewModel.fArrivalTime = tProduct.fArrivalTime;
            pdViewModel.fCategory = tProduct.fCategory;
            pdViewModel.fDescription = tProduct.fDescription;

            pdViewModel.fFirstName = tPMemberShip.fFirstName;
            pdViewModel.fLastName = tPMemberShip.fLastName;

            //pdViewModel.fPname = tPDetails.fPName;

            pdViewModel.fImgPath = db.tProductImage.Where(p => p.fProductID == fProductID && p.fCover == true).Select(p => p.fImgPath).FirstOrDefault();
            pdViewModel.fPname = db.tProductDetails.Where(p => p.fProductID == fProductID).Select(p => p.fPName).FirstOrDefault();

            foreach (var f in tPImages)
            {
                pdViewModel.listImgPath.Add(f.fImgPath);
            }

            foreach (var f in tPDetails)
            {
                pdViewModel.listStyle.Add(f.fPName);
            }

            return View(pdViewModel);
        }
    }
}

gogobuy/gogobuy/Views/Details/BucketListDetails.cshtml
@model gogobuy.ViewModels.ProductDetailsViewModel
@{ ViewBag.Title = "BucketListDetails"; }

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" type="text/css" href="~/Content/css/BucketListDetails.css">
<section class="container sproduct my-5 pt-5">
    <div class="row mt-5">
        <div class="col-lg-5 col-md-12 col-12">
            <img class="img-fluid rounded w-100 pb-1" src="~/Content/img/Product/@Model.fImgPath" id="Main-Img" alt="">
            <div class="small-img-group">
                <div class="small-img-col">
                    <img src="" style="width:100%" class="small-Img rounded" alt="">
                </div>
                <div class="small-img-col">
                    <img src="" style="width:100%" class="small-Img rounded" alt="">
                </div>
                <div class="small-img-col">
                    <img src="" style="width:100%" class="small-Img rounded" alt="">
                </div>
            </div>
        </div>


        <div class="col-lg-6 col-md-12 col-12">
            <h6>@Model.fCategory</h6>
            <h3 class="py-4">@Model.fProductName</h3>
            <h6><i class="iconRequest fas fa-edit"></i>需求數量：@Model.fQuantity 個</h6>
            <h6 class="my-3"><i class="iconRequest fas fa-grin-beam"></i>買家：@Model.fFirstName@Model.fLastName</h6>
            <h6 class="my-3"><i class="iconRequest fas fa-map-marker-alt"></i>買家所在地：@Model.fProductLocation</h6>
            <h6 class="my-3"><i class="iconRequest fas fa-truck"></i>可接受到貨時間：@Model.fArrivalTime</h6>
            <h4 class="py-3">可接受價格：<span class="dollars">NT @String.Format("{0:0}", Model.fPrice) 元 / 個</span></h4>
            <a href="~/Chatroom/Chatroom?fMemberID=@Model.fMemberID" class="link-success">
                @{

                                @Html.ActionLink("聯繫買家", "Chatroom", "Chatroom", new { fMemberID = Model.fMemberID }, new { @class = "btn btn-success" }) }
            </a>
            @*<button class="btn btn-danger"><i class="fas fa-heart"></i> 幫忙代買！</button>*@
        </div>
    </div>
</section>
<!-- product main section -->
<!-- Tabs -->
<div class="container">
    <h2 class="py-3 text-center">產品描述</h2>
    <div class="row py-4 justify-content-center">
        <div class="col-md-8">
            <ul class="nav nav-tabs" id="ProductTab">
                <li class="nav-item">
                    <a href="" class="nav-link active" data-bs-toggle="tab" data-bs-target="#productDetails">
                        Description
                    </a>
                </li>
            </ul>
            <div class="tab-content py-3" id="ContentTab">
                <div class="tab-pane fade show active" id="productDetails">
                    <div class="container-fluid pDetails row">
                        <div class="detailsText">
                            <p class="mx-auto">@Model.fDescription</p>
                        </div>
                        <div class="detailsPicture">
                            <img class="pPicture img-fluid mx-auto img-thumbnail" src="~/Content/img/Product/@Model.fImgPath" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Tabs -->

gogobuy/gogobuy/Views/Details/ProductDetails.cshtml
@model gogobuy.ViewModels.ProductDetailsViewModel

@{ ViewBag.Title = "ProductDetails"; }
<head>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.13.0/css/all.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/ProductDetails.css">
    <style>
        .toast {
            left: 0;
            margin: auto;
            position: fixed;
            right: 0;
            text-align: center;
            width: 170px;
            z-index: 1;
            top: 40%;
        }
    </style>
</head>
<section class="container sproduct my-5 pt-5">
    <div class="row mt-5">
        <div class="col-lg-5 col-md-12 col-12">
            <img class="img-fluid rounded w-100 pb-1" src="~/Content/img/Product/@Model.fImgPath" id="Main-Img" alt="">
            <div class="small-img-group">
                @{ foreach (var imgPath in Model.listImgPath)
                    {
                        <div class="small-img-col">
                            <img src="~/Content/img/Product/@imgPath" style="width:100%" class="small-Img rounded" alt="">
                        </div> } }
                @*<div class="small-img-col">
                        <img src="~/Content/img/Product/f.fImgPath" width="100%" class="small-Img rounded" alt="">
                    </div>*@
                @*<div class="small-img-col">
                            <img src="~/Content/img/ProductDetails/sneakers2.jpg" width="100%" class="small-Img rounded" alt="">
                        </div>
                        <div class="small-img-col">
                            <img src="~/Content/img/ProductDetails/sneakers3.jpg" width="100%" class="small-Img rounded" alt="">
                    </div>*@
            </div>
        </div>


        <div class="col-lg-6 col-md-12 col-12">
            @*<h6>鞋子類</h6>*@
            <h6>@Model.fCategory</h6>
            @*<h3 class="py-4">東京限定Nike鞋</h3>*@
            <h3 class="py-4">@Model.fProductName</h3>
            @*<h2>NT$ 3999.00 元</h2>*@
            <h2>NT @String.Format("{0:0}", Model.fPrice) 元</h2>

            @*@{ foreach (var pStyle in Model.listStyle)
                            {
                                if ( Model.fPname != null)
                                {
                                    <select class="my-3">
                                    <option>選擇樣式</option>
                                    <option>@Model.fPname</option>
                                    </select>
                                }
                        } 
              }*@
            <input type="number" value="1" min="1" max="@Model.fQuantity" />
            <button class="btn buy-btn">
                <span class="me-2">加入購物車</span><i class="fas fa-shopping-cart"></i>
            </button>
            @{
                if (Model.isLike)
                {
                    <button class="btn btn-danger like" id="@Model.fProductID">
                        <span class="me-2">已收藏</span> <i class="fas fa-heart"></i>
                    </button>
                }
                else
                {
                    <button class="btn btn-outline-danger like" id="@Model.fProductID">

                        <span class="me-2">加入收藏</span> <i class="fas fa-heart"></i>
                    </button>
                }
            }

            <h6 class="my-3">賣家：@Model.fFirstName@Model.fLastName</h6>
            <h6 class="my-3">商品所在地：@Model.fProductLocation</h6>
            <h6 class="my-3">到貨時間：@Model.fArrivalTime</h6>
        </div>
    </div>
</section> <!-- product main section --> <!-- Tabs -->
<div class="container">
    <h2 class="py-3 text-center">產品描述</h2>
    <div class="row py-4 justify-content-center">
        <div class="col-md-8">
            <ul class="nav nav-tabs" id="ProductTab">
                <li class="nav-item">
                    <a href="" class="nav-link active" data-bs-toggle="tab" data-bs-target="#productDetails">
                        產品詳細資訊
                    </a>
                </li>
                <li class="nav-item">
                    <a href="" class="nav-link" data-bs-toggle="tab" data-bs-target="#comments">
                        評論
                    </a>
                </li>
            </ul>
            <div class="tab-content py-3" id="ContentTab">
                <div class="tab-pane fade show active" id="productDetails">
                    <div class="container-fluid pDetails row">
                        @*<div class="detailsPicture">
                                <img class="pPicture img-fluid mx-auto img-thumbnail" src="" alt="">
                            </div>*@
                        <div class="detailsText">
                            <img class="img-fluid rounded w-100 pb-1" src="~/Content/img/@Model.fImgPath" id="Main-Img" alt="">
                            <p class="mx-auto">@Model.fDescription</p>
                        </div>
                    </div>
                    <div class="container-fluid pDetails row">
                        @*<div class="detailsText">
                                <p class="mx-auto">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam quibusdam dolore nam, obcaecati qui molestiae libero laudantium soluta ullam, nesciunt ad fuga. Minus dolor sunt aliquam minima possimus nam quam mollitia saepe non recusandae? Laboriosam ratione debitis dignissimos error aperiam, ipsam expedita eius quisquam facere earum ut eos magni odio.</p>
                            </div>*@
                        @{ foreach (var imgPath in Model.listImgPath)
                            {
                                <div class="detailsPicture">
                                    <p>
                                        <img class="pPicture img-fluid mx-auto img-thumbnail" src="~/Content/img/Product/@imgPath" alt="">
                                    </p>
                                </div> } }
                    </div>
                    <div class="container-fluid pDetails row">
                        @*<div class="detailsText">
                                <p class="mx-auto">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam provident harum earum expedita optio dignissimos?</p>
                            </div>*@
                        @*<div class="detailsPicture">
                                <img class="pPicture img-fluid mx-auto img-thumbnail" src="~/Content/img/Product/@imgPath" alt="">
                            </div>*@
                        @*<div class="detailsText">
                                <p class="mx-auto">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat, quidem?</p>
                                <p class="mx-auto">Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi corporis error expedita modi necessitatibus officia repellat! Sunt explicabo obcaecati sed quis possimus velit eius omnis?</p>
                            </div>*@
                    </div>
                </div>
                <div class="tab-pane fade" id="comments">
                    There is no comment yet.
                </div>
            </div>
        </div>
    </div>
</div> <!-- Tabs -->
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="d-flex justify-content-end">
                <button type="button" class="btn-close m-2" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                要使用此功能，請先登入會員！
            </div>
            <div class="d-flex justify-content-end">
                <button type="button" class="btn btn-outline-secondary m-2" data-bs-dismiss="modal">關閉</button>
                <a href=@Url.Action("Login", "home") class="btn btn-primary  m-2">登入</a>
            </div>
        </div>
    </div>
</div>
<!-- Toast -->
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
    </symbol>
</svg>
<div class="toast alert-success" data-animation="true" data-autohide="false" id="myToast">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill" /></svg>
    <div class="toast-body">
        已加入購物車!
    </div>
</div>
<script>
    $('.buy-btn').click(function () {
        $.ajax({
             url: "@Url.Action("AddToCart", "ShoppingCart")",
             type: 'post',
             data: {
                productID: "@Model.fProductID"
             },
             async: true,
             success: function (data) {
                 if (data == 'success') {
                     $('#myToast').toast('show');
                     setTimeout(function () {
                         $('.toast').toast('hide');
                     }, 1000);
                 }
                 if (data == 'login') {
                     $('#myModal').modal('show');
                 }
             }
         });
        
    });
     $('button.like').click(function () {
     var productID = this.id;
     if ($(this).children('span').text() == '加入收藏') {
         $.ajax({
             url: "@Url.Action("LikeItem", "Collect")",
             type: 'post',
             data: {
                 productID: productID
             },
             async: true,
             success: function (data) {
                 if (data == 'success') {
                     $('#' + productID).children('span').text("已收藏");
                     $('#' + productID).removeClass('btn-outline-danger');
                     $('#' + productID).addClass('btn-danger');
                 }
                 if (data == 'login') {
                     $('#myModal').modal('show');
                 }
             }
         });
     } else {
         $.ajax({
             url: "@Url.Action("Delete", "Collect")",
             type: 'post',
             data: {
                 productID: productID
             },
             async: true,
             success: function (data) {
                 $('#' + productID).children('span').text("加入收藏");
                 $('#' + productID).removeClass('btn-danger');
                 $('#' + productID).addClass('btn-outline-danger');
             }
         });
     }
 });

 var MainImg = document.getElementById("Main-Img");
 var smallImg = document.getElementsByClassName("small-Img");

 smallImg[0].onclick = function () {
     MainImg.src = smallImg[0].src;
 };

 smallImg[1].onclick = function () {
     MainImg.src = smallImg[1].src;
 };

 smallImg[2].onclick = function () {
     MainImg.src = smallImg[2].src;
 };

</script>